### PR TITLE
Updated UI to handle Previous Played and Mute Commercials

### PR DESCRIPTION
**Pull request by gravesjohnr**
A whole new layout designed for a 7" screen, but should work for most screen sizes.
I added the ability to mute/pause during commercials.  It is able to do this because most stations return a 204 call on "Currently Playing" when there are long talk sessions or commercials.
Here are some screenshots.
2020-06-10-203700_800x480_scrot

2020-06-11-212220_800x480_scrot

2020-06-11-225445_800x480_scrot

### CODE REVIEW

**Comment by johnbartkiw** [comment]
It looks like you moved the set_urls() call back to __init__.

Was that intentional or any chance you missed the PR from Kris that was merged yesterday?

**Comment by gravesjohnr** [comment]
Oh... I didn't see the PR yesterday.  Let me have a look.
I don't recall which way is  "right" now with the core changes.  Do I have it backwards?

**Comment by gravesjohnr** [comment]
I was trying to resolve, but I don't recall the procedure.  Do I have to resync fork, remake changes then recreate the pr?  I tried using the editor and creating a branch, but that failed.

**Comment by gravesjohnr** [comment]
Let me just try again.  I've done the merge upstream, made changes, now I'll recreate the pr.

**Pull request closed without merging**
