### PR TITLE
New UI layout and added mute commercials

### PR DESCRIPTION
**Pull request by gravesjohnr**
A whole new layout designed for a 7" screen, but should work for most screen sizes.
I added the ability to mute/pause during commercials. It is able to do this because most stations return a 204 call on "Currently Playing" when there are long talk sessions or commercials.
Here are some screenshots.

2020-06-10-203700_800x480_scrot

2020-06-11-212220_800x480_scrot

2020-06-11-225445_800x480_scrot

### CODE REVIEW

**Comment by johnbartkiw** [comment]
Again I can't test this so I'm accepting it blind since everything looks decent. What type of device are you using with a screen? I'm tempted to set something up to take advantage of this.

**Comment by gravesjohnr** [comment]
John,
Thanks for that.
I would be very interested to know if this breaks the non-ui devices.  I don't think it will.
I'm using a pi4 with the stock 7" screen.  One-by-one, I'm getting the functionality I'm used to on my echo show device.  I really want to get rid of my echos. :)
-John

**Comment by johnbartkiw** [comment]
Do you have info on the full setup? Specifically if you're using piCroft and what microphone HW you're using?
My use of Mycroft is to get rid of my Google Home devices and while the Mark I gets most of the way there I still haven't fully cut the cord. This could help. :)

**Comment by gravesjohnr** [comment]
John,
I just started working on this.  I plan to do a write-up and provide an image when I'm done.

Basically I'm using a
- Pi4 ($50)
- 7" Screen ($60)
- Fan case/power supply($20)
- Microphone ($32)
- Speaker ($20)
 (All up $182).  I wanted to keep it under $150. :(

I stared with PiCroft, but couldn't get the UI to work.  It needs KDE Plasma.
I'm going back-n-forth on the use of kubuntu vs kde plasma bigscreen for the base OS.  Bigscreen has a bunch of things I don't need and I'm finding it difficult to install what I do need.  Kubuntu is great, but does cause some heating issues; which I think I've sorted out.  Kubuntu gives me full control and I'm able to get things to do exactly what I want.
My goal is simple, to replace my 5" echo show.  Eventually having a "dot" style would be nice too.
The main uses of the echo today are:
- Todoist (works - need to add UI compoents)
- IHeartRadio (works)
- YouTube (Almost works!)
- Spotify (Works)
- Weather (Works, but I don't like the UI)
- Timer / Alarm (Works, but I'd like to add a nice UI)
- HomeAssistant (Works for basic things.  I want to add the ability to view cameras and floorplan layouts)
-John

**Pull request merged**
