### PR TITLE
Add UI Components

### PR DESCRIPTION
**Pull request by gravesjohnr**
This pull request adds radio station art/description and current track art/artist/track/album information on a UI if one exists.

### CODE REVIEW

**Comment by johnbartkiw** [comment]
I can't test this on my Mark I so I'm going to blindly accept and trust that you've tested it all :)

**Comment by gravesjohnr** [comment]
I've done quite a bit more work on the screens.  I'll clean things up and setup a new PR.
2020-06-10-203700_800x480_scrot

**Comment by johnbartkiw** [comment]
That looks amazing! Now you're making me want to get a Mark II :)

**Comment by krisgesling** [comment]
Hey John (and John),

Loving this UI, excellent work!

I mentioned it to @AIIX who's one of the core developers of the Qt GUI Framework and he's happy to help, provide pointers etc. You can [reach him on Mycroft Chat](https://chat.mycroft.ai/community/messages/@aix) if that would be helpful.

Thanks :)

**Pull request merged**
